### ISSUE TITLE
how to patch the images into gltf?

### ISSUE THREAD

**Issue by yoyokeen** [KhronosGroup/COLLADA2GLTF#101]
./collada2gltf -f ./DAE  ./images -o ./Data/b.gltf -e

thant can work well, but the b.gltf loaded without images.
what's the problem?

**Comment by donmccurdy** [comment]
@yoyokeen the `-f` flag should only point to the `.dae` file. If that file has references to image files, they will be automatically used.

```
./collada2gltf -f path/to/foo.dae -o foo.gltf -e
```

If that isn't working, then make sure the images are used correctly in the COLLADA file itself by testing it with a free COLLADA viewer like [FBX Review](https://www.autodesk.com/products/fbx/fbx-review). If the COLLADA file seems right, but the `.gltf` file doesn't show images when you load it with [online](https://gltf-viewer.donmccurdy.com/) [viewers](sandbox.babylonjs.com), then could you post the COLLADA file and textures here so we can debug? Note that you can drag-and-drop .ZIP files into GitHub comments.
