### ISSUE TITLE
How to install converter collada to gltf format locally?

### ISSUE THREAD

**Issue by sabahMotamedi** [KhronosGroup/COLLADA2GLTF#11]
I don't know how to install it,  please if you have any tutorial for install it send me

**Comment by javagl** [comment]
There are already issues that are strongly related: https://github.com/KhronosGroup/COLLADA2GLTF/issues/1 , https://github.com/KhronosGroup/COLLADA2GLTF/issues/2 and for Windows: https://github.com/KhronosGroup/COLLADA2GLTF/issues/8 . 

In doubt, https://cesiumjs.org/convertmodel.html can be used, but I'm not sure about the versions/state of the libraries that are used under the hood there.


@pjcozzi @tfili @lexaknyazev 
Assuming that #2 will be tackled later: Is there (technically) the option to provide updated binaries? (I could provide the Win64 one, if necessary - the "snapshot" that I mentioned in #1 is not the most sustainable solution here). Certainly, the schedule is tight (updates for 1.1, holidays, etc.) but the lack of a converter that can simply be downloaded and started (out-of-the-box) may be an unnecessary impediment for adopters.

**Comment by pjcozzi** [comment]
@sabahMotamedi there are binaries here: https://github.com/KhronosGroup/glTF/releases

> Assuming that #2 will be tackled later: Is there (technically) the option to provide updated binaries?

Yes, it is just a matter of someone having the time to do it.  @tfili and I are spread thin.  Anyone is welcome to contribute here.

Closing this as a duplicate with those linked above.
