### ISSUE TITLE
creating translucent model, from opaque model

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/COLLADA2GLTF#115]
Replaces https://github.com/KhronosGroup/glTF/issues/373

I`m trying to convert collada file using collada2gltf.exe v 0.8, but output model is translucent when i open it by the Cesium.

Add link for the archive with model files and screenshoot : https://www.dropbox.com/s/i8f6mfybx4d4pd1/converter.zip?dl=0

**Comment by lasalvavida** [comment]
Link is broken and OP has deleted their account. Closing since I don't have an effective way to follow up.
