### ISSUE TITLE
converting dae that has units in centimeters

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/COLLADA2GLTF#118]
Replaces https://github.com/KhronosGroup/glTF/issues/460 by @toloudis

---

>I have a DAE that has a trivial animation (a few simple meshes separated in space, 2 keys, doing a simple translate and rotate) and the geometry comes through with apparently bad transforms.  If I change the line
 `<unit name="centimeter" meter="0.01"/>`
to
`<unit name="meter" meter="1.0"/>`
and move my camera appropriately, 
the conversion looks perfectly good.
>
>Since there is no stock viewer for 1.0 yet, I am not sure if it's my viewer or the conversion that is bad.  The DAE looks correct in any viewer I try.

---

>Attached is the model. Just remove the `.txt` extension.
>
>[test.dae.txt](https://github.com/KhronosGroup/glTF/files/18830/test.dae.txt)

**Comment by lasalvavida** [comment]
This appears to not be an issue in the new converter.

![image](https://user-images.githubusercontent.com/2489570/39103667-1507233e-467a-11e8-80bf-753625311547.png)

Model looks the same with both units specified and the animation functions as expected, closing.
