### ISSUE TITLE
Converted Models Have Non-unique IDs

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/COLLADA2GLTF#119]
Replaces https://github.com/KhronosGroup/glTF/issues/488 by @tparisi 

---

>Check out Cesium Man for example: it has both a buffer and a node with the ID `Cesium_Man`. This is illegal and I think it's causing my Three.js loader some problems.
>
>From the spec:
>
>IDs for top-level glTF dictionary objects (`accessors`, `animations`, `buffers`, `bufferViews`, `cameras`, `images`, `materials`, `meshes`, `nodes`, `programs`, `samplers`, `scenes`, `shaders`, `skins`, `techniques`, and `textures`) are in the same namespace and are unique. 

---

Is this still an issue in the 2.0 branch?

**Comment by donmccurdy** [comment]
The Cesium Man model now contains only a `mesh` named `Cesium_Man`, the nodes are unnamed. But even if it were, I don't believe we're requiring `name` to be unique, and IDs are now indices.

It's still _preferable_ if the names are unique (three.js animation may have issues when this isn't true, for example) but not required, so I think this can be closed.

**Comment by pjcozzi** [comment]
Sounds good, thanks @donmccurdy!
