### ISSUE TITLE
Vertex color buffer not converted correctly

### ISSUE THREAD

**Issue by stevenvergenz** [KhronosGroup/COLLADA2GLTF#12]
When converting a Collada file with vertex colors (exported from blender, verified to work with three.js), the color buffer comes through, is listed correctly as a bufferview/accessor/mesh attribute, but the contents of the buffer are zeroed out.

You can see this in the .bin file in the attached zip at byte offset 13608, which is where the color buffer in the .gltf file points. The corresponding buffer in the Collada file is on line 127.

Command used to convert: `collada2gltf -k -f playermeter.dae`

Sample models: [playermeter.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/685634/playermeter.zip)

**Comment by javagl** [comment]
The "unlikely" case in https://github.com/KhronosGroup/COLLADA2GLTF/blob/2f512d1f9645cb3890904109ecd311edf90b4e4a/convert/meshConverter.cpp#L248 applies here. This can (probably(!)) be fixed easily, by changing the surrounding

    if (allowedComponentsPerAttribute != componentsPerElement)

to 

    if (allowedComponentsPerAttribute < componentsPerElement)

and omitting the inner `if`. At least, then a proper accessor with the `GL_FLOAT` `"VEC3"` RGB color data from the COLLADA file seems to be generated. 

But there seems to be something else odd with the result. I'm not sure ATM whether the common material extension is supposed to support vertex colors (but don't think so). And without using the extension, the generated shaders don't have a "color" attribute either. Someone will have to take another look at this....

**Comment by pjcozzi** [comment]
@stevenvergenz @javagl if that fix works, please submit a pull request.

@stevenvergenz as a workaround, if OBJ is sufficient for you, maybe try [obj2gltf](https://github.com/AnalyticalGraphicsInc/obj2gltf).

Also, for tips on fixing the COLLADA (if it just so happens that three.js' loader has a workaround, etc.), see [here](http://cesiumjs.org/tutorials/3D-Models-Tutorial/#converting-collada-to-gltf).

**Comment by stevenvergenz** [comment]
@javagl Realistically, it's nearly as easy to overwrite the glTF material in my consumer application as it is to make the KHR common material work. If that's a complication, I can omit the material altogether. As long as the color buffer goes through, I can find a way to use it.

@pjcozzi I've never actually used OBJ models before, so I'd like to avoid having to learn how they work if it's just gonna be an intermediate format anyway. That said, I'll give it a go if this issue can't be solved yet.

**Comment by javagl** [comment]
If desired, I could create a PR, but my change was rather a guess, and although it seemed to work afterwards, someone with a deeper understanding of COLLADA2GLTF should have a look at this.

**Comment by donmccurdy** [comment]
+1 on this; I tested the fix above and it worked for my workflow with MagicaVoxel, although I needed to replace the KHR common material at runtime. But I also don't know COLLADA2GLTF well enough to guess at whether the change is really the right one. :/

**Comment by ilkedemir** [comment]
Following the issue, please [see a similar problem about vertex colors](https://github.com/AnalyticalGraphicsInc/obj2gltf/issues/102). Is there a fix coming soon?

**Comment by lasalvavida** [comment]
Vertex colors in this model are converted correctly in v2.1.2. Closing.

![image](https://user-images.githubusercontent.com/2489570/39102314-a7316404-4670-11e8-9170-cb8468f23bff.png)
