### ISSUE TITLE
Converter Exporting Phong Instead of Constant for Unlit Common Materials Export

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/COLLADA2GLTF#120]
Replaces https://github.com/KhronosGroup/glTF/issues/511 by @tparisi 

---

> Looking at the Cesium Milk Truck model's base glTF, which doesn't have lighting, and then the Common Materials version, it seems like collada2gltf isn't correctly exported the material. The exported materials should be using the technique "CONSTANT" but the materials in the file all have "PHONG" instead.

---

OBE with glTF 2.0 PBR and perhaps https://github.com/KhronosGroup/glTF/pull/1163

**Comment by lasalvavida** [comment]
> The exported materials should be using the technique "CONSTANT"

That isn't correct. The COLLADA source model specifies phong shading for all materials which is why phong shading is used in the glTF after conversion.

Closing.
