### ISSUE TITLE
collada2gltf segfault with -k switch (KHR_materials_common)

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/COLLADA2GLTF#124]
Replaces https://github.com/KhronosGroup/glTF/issues/652 by @timknip

---

In particular, see https://github.com/KhronosGroup/glTF/issues/652#issuecomment-249164529

---

Perhaps not an issue with the glTF 2.0 PBR branch and in the future with https://github.com/KhronosGroup/glTF/pull/1163

**Comment by lasalvavida** [comment]
This is no longer and issue in the new converter.
