### ISSUE TITLE
collada2gltf producing different gltf outputs

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/COLLADA2GLTF#126]
Replaces https://github.com/KhronosGroup/glTF/issues/669 by @slozier

---

>For certain files it seems collada2gltf does not always produce the same gltf output. I tried the latest collada2gltf release as well as running from the latest commit. The issue only occurs in release mode when running from source so my guess is some uninitialized memory in the buffer element...
>
>I've attached the test file:
[bad.zip](https://github.com/KhronosGroup/glTF/files/397704/bad.zip)
>
>As you can see below, it's producing a different file hash:

```
E:\> .\collada2gltf\collada2gltf.exe -f bad.dae -e
converting:bad.dae ... as bad.gltf
[geometry] 496 bytes
[animations] 0 bytes
[scene] total bytes:496
[completed conversion]
Runtime: 0.01 seconds
E:\> write-host (Get-FileHash bad.gltf).Hash
9541A32347553BCDE95991674979269C1DB4205DFA0085F8A5E4DC378D3E40C4
E:\> .\collada2gltf\collada2gltf.exe -f bad.dae -e
converting:bad.dae ... as bad.gltf
[geometry] 496 bytes
[animations] 0 bytes
[scene] total bytes:496
[completed conversion]
Runtime: 0.01 seconds
E:\> write-host (Get-FileHash bad.gltf).Hash
74FCBE213F46F550CBA51087CF01609684A432866316E39516C5D057B20E69F7
E:\> .\collada2gltf\collada2gltf.exe -f bad.dae -e
converting:bad.dae ... as bad.gltf
[geometry] 496 bytes
[animations] 0 bytes
[scene] total bytes:496
[completed conversion]
Runtime: 0.01 seconds
E:\> write-host (Get-FileHash bad.gltf).Hash
F5ED7790884CA17B9C9592C464C4025B16A8B7ADDBA864B7BFE6EAB6A05374BA
```

---

Is this still an issue in the 2.0 branch?

**Comment by donmccurdy** [comment]
Didn't check hashes but re-running the generation script from the sample models "tools" branch isn't causing any changes visible to Git, I think this can be closed.

**Comment by lasalvavida** [comment]
This should not be an issue in 2.0, closing.
