### ISSUE TITLE
COLLADA2glTF Ignores -o Flag

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/COLLADA2GLTF#127]
Replaces https://github.com/KhronosGroup/glTF/issues/672 by @KermMartian 

---

> COLLADA2glTF ignores the output path specified with the -o flag, instead just generating the output in the path computed by replacing the .dae in the input file with .gltf. To replicate, try (for example) the following:
`./foo/collada2gltf -r -e -f struct.dae -o struct.ascii.gltf -c Open3DGC -m ascii
converting:struct.dae ... as struct.gltf`

---

Is this still an issue in the 2.0 branch?

**Comment by KermMartian** [comment]
This is resolved on the 2.0 branch and can be closed.
