### ISSUE TITLE
Support multiple animations

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/COLLADA2GLTF#130]
Following changes in #102, all COLLADA animation clips are now always grouped together into a single glTF animation.  These should be broken out into separate glTF animations.

**Comment by donmccurdy** [comment]
Copying over https://github.com/KhronosGroup/COLLADA2GLTF/issues/112 -

> Carried over from https://github.com/KhronosGroup/glTF/issues/300 and #66, if a COLLADA asset contains [<animation_clip/>](https://www.khronos.org/collada/wiki/Animation_clip_OpenCOLLADA_extension) nodes, we should write each to a separate `animations` entry in the glTF output.

**Comment by lasalvavida** [comment]
Found a model with `animation_clip` for testing in the [assimp test models](https://github.com/assimp/assimp/blob/c98915e38295b7af660f15b43a38a9d6cb390d4f/test/models/Collada/library_animation_clips.dae)

**Comment by lasalvavida** [comment]
Unfortunately, OpenCOLLADA doesn't have code for parsing animation clips, only for writing them. Ultimately they probably need proper support over there, but it may be simpler in the short term to put something together in the extras handler here for now.
