### ISSUE TITLE
build is broken with rapidjson (Writer is private)

### ISSUE THREAD

**Issue by themaddoctor** [KhronosGroup/COLLADA2GLTF#134]
Rapidjson is missing from the collada2gltf sources, so I installed the latest one, which is 1.1.0.

g++ -c main.cpp -I ../include     -I /usr/include/opencollada/COLLADAFramework     -I /usr/include/opencollada/COLLADABaseUtils     -I /usr/include/opencollada/COLLADASaxFrameworkLoader     -I /usr/include/opencollada/GeneratedSaxParser     -I /usr/include/opencollada/COLLADAStreamWriter     -I ../GLTF/include
main.cpp: In function ‘int main(int, const char**)’:
main.cpp:180:103: error: ‘rapidjson::Writer<OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags>::Writer(const rapidjson::Writer<OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags>&) [with OutputStream = rapidjson::GenericStringBuffer<rapidjson::UTF8<> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator; unsigned int writeFlags = 0]’ is private within this context
 n::Writer<rapidjson::StringBuffer> jsonWriter = rapidjson::Writer<rapidjson::StringBuffer>(s);
                                                                                             ^
In file included from /usr/include/rapidjson/prettywriter.h:18:0,
                 from main.cpp:6:
/usr/include/rapidjson/writer.h:471:5: note: declared private here
     Writer(const Writer&);
     ^~~~~~

Here's a snippet from /use/include/rapidjson/writer.h:
private:
    // Prohibit copy constructor & assignment operator.
    Writer(const Writer&);
    Writer& operator=(const Writer&);

**Comment by lasalvavida** [comment]
@themaddoctor, we include rapidjson as a submodule, you have to

```bash
git submodule update --init --recursive
```

like it says in the README.

This may be an issue when we update the version of rapidjson we depend on, but no the cmake build that I support here is not broken.

**Comment by lasalvavida** [comment]
I am going to close this, feel free to reopen it if you feel like I've missed something.

**Comment by lasalvavida** [comment]
Also probably worth mentioning

```bash
git submodule update --init --recursive
```

To pull update submodules if you still don't have rapidjson in the source tree
