### ISSUE TITLE
How Can I use Base64 code to convert the jpeg in gltf?

### ISSUE THREAD

**Issue by VersusRain** [KhronosGroup/COLLADA2GLTF#136]
How can I use Base64 code to convert the jpeg in gltf file?
scan  some options  but  doesn't work !  like  -e -m, etc
It's just a path in the gltf file now.

**Comment by lasalvavida** [comment]
Hi @VersusRain. This project is for converting COLLADA files (DAE) to glTF, not for processing files that are already glTF if I'm understanding your question correctly.

Maybe take a look at [gltf-pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline).

**Comment by emackey** [comment]
My info may be old, but I think the `-s` (separate) commandline flag causes separate files like JPG files, and without it the default behavior is (or was?) that textures will be embedded in base64.

**Comment by VersusRain** [comment]
thanks guys
