### ISSUE TITLE
Model broken after transfer to glb format?

### ISSUE THREAD

**Issue by seanexplus** [KhronosGroup/COLLADA2GLTF#158]
I use collada2gltf with flag -b -m=true to transfer a  collada model, but the result is broken.
original collda model
![image](https://user-images.githubusercontent.com/4726274/37414471-269de1aa-27e4-11e8-8aa0-32d736a95537.png)
transfered glb 
![image](https://user-images.githubusercontent.com/4726274/37414515-4475baa4-27e4-11e8-81d7-962dbadf5398.png)
Any suggestion about tuning the original collada file or command line flags to get the right glb file?

**Comment by donmccurdy** [comment]
Would you be able to share the COLLADA file? You can drag-and-drop .ZIP files into GitHub comments.

**Comment by seanexplus** [comment]
This is the collada file.
[STR_issue.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/1811970/STR_issue.zip)

**Comment by RemiArnaud** [comment]
dae looks legit and quite simple in fact (one mesh)

so its probably a bug in a t-mesher or the likes.

**Comment by lasalvavida** [comment]
Looks like indices are probably overflowing UINT16. Once either #137 is completed or some other PR implements UINT32 indices I think this should convert correctly.

@seanexplus for now if you can break your COLLADA mesh up into smaller, separate meshes or primitives that should work.

**Comment by seanexplus** [comment]
After split the one big mesh into several small piece, problem disappeared. Thank you.

**Comment by lasalvavida** [comment]
This should be fixed by #159 which is included in the 2.1.0 release if you're looking for a precompiled binary. Closing
