### ISSUE TITLE
Mime type incorrect

### ISSUE THREAD

**Issue by lilleyse** [KhronosGroup/COLLADA2GLTF#162]
When converting the duck model the mime type of the image data uri is incorrect.

`"uri": "data:image/.png;base64,` should be `"uri": "data:image/png;base64,`

[duck.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/1831798/duck.zip)

**Comment by lasalvavida** [comment]
@lilleyse, what system and version of the c++ std lib for your platform did you run the converter on?

We use std::filesystem to split off the file extension and I haven't seen it include the period before.

**Comment by lilleyse** [comment]
I used the latest version of Visual Studio 2017. Not sure what the version number is but I can check later.

I original noticed this problem on the [Cesium online converter](http://52.4.31.236/convertmodel.html) which I believe uses a version built from VS 2015.

If it helps I can try debugging later today.

**Comment by lexaknyazev** [comment]
The same issue showed here: https://github.com/donmccurdy/three-gltf-viewer/issues/81.

**Comment by Ziriax** [comment]
Indeed, I noticed the same problem with our Maya2glTF exporter recently (it uses the same GLTF library)

**Comment by lasalvavida** [comment]
It looks like #147 broke png detection, so it falls back to using the extension. We definitely want to drop the period when using extensions to build mime types, but png detection needs to be fixed as well.

**Comment by lasalvavida** [comment]
I should have been more thorough before merging in #147.

**Comment by lasalvavida** [comment]
Fixed in #164.
