### ISSUE TITLE
Morph target support

### ISSUE THREAD

**Issue by lasalvavida** [KhronosGroup/COLLADA2GLTF#166]
1. Make/find & license a simple COLLADA model with morph targets
    * Preferably make a COLLADA model that is analogous to this simple glTF sample model: [AnimatedMorphCube](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphCube)

2. Add conversion support for generating glTF morph targets

**Comment by pjcozzi** [comment]
@sbtron does Microsoft have any simple COLLADA models with morph targets we could use?  Or could a tech artist make one? 👍

**Comment by Ziriax** [comment]
I made a couple of very simple morph target scenes for Maya, with and without animation, with and without skinning, if these are of any help, I can export these to DAE if you want.

**Comment by lasalvavida** [comment]
That would be awesome and much appreciated @Ziriax!

**Comment by bghgary** [comment]
> does Microsoft have any simple COLLADA models with morph targets we could use?

I have the source fbx used to generate the AnimatedMorphCube and AnimatedMorphSphere. Should be easy to put them into blender and get a COLLADA file out of them. Would that help?

**Comment by lasalvavida** [comment]
> I have the source fbx used to generate the AnimatedMorphCube and AnimatedMorphSphere. Should be easy to put them into blender and get a COLLADA file out of them. Would that help?

Absolutely, more test models is always better.

**Comment by bghgary** [comment]
Err, scratch that. We did the animation inside Unity, so it will not be super easy to get them into COLLADA unless we can export to COLLADA from Unity.

**Comment by RemiArnaud** [comment]
Yes you can. 

https://assetstore.unity.com/packages/3d/characters/collada-exporter-for-unity2017-99793


Regards
-- Rémi

**Comment by lilleyse** [comment]
@soadzoor submitted a morph target test model to https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/365.

[animation_test.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/1960794/animation_test.zip) contains a .blend source file and exported .dae file, which _looks_ correct.

@soadzoor would it be ok to use this model for testing here?

**Comment by soadzoor** [comment]
@lilleyse I guess/hope so. I'm not the one who created it. I believe it's part of the official [glTF-Blender-Exporter - scene examples](https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/scenes) (`01_morphed_cube.blend` -> this is the one)

I only made some minor changes to the color values

**Comment by lasalvavida** [comment]
@soadzoor, it looks like the attached exported COLLADA doesn't have animations. I'd like to use this to test #206 if there's any chance you could re-export it with the animations?

**Comment by soadzoor** [comment]
@lasalvavida Hmm.. I cannot find an option to export animations as well, when it comes to DAE.. Is it possible that blender doesn't support it? I tried to google for answers with no luck

**Comment by lasalvavida** [comment]
Closed by #206
