### ISSUE TITLE
Support alpha/transparency properly

### ISSUE THREAD

**Issue by lasalvavida** [KhronosGroup/COLLADA2GLTF#168]
Parent issue for #121, #105, #7. 

Make sure 2.0 alphaMode and alphaCutoff convert correctly, and that transparency maps are handled properly.

**Comment by lasalvavida** [comment]
This should also handle 1.0 cases with glsl and materials common to resolve #176.

**Comment by KermMartian** [comment]
I apologize if this is a question that has been elsewhere, but I'm afraid I haven't found it following the graph of issues referencing transparency. Neither having `<transparency>(value less than 1.0)</transparency>` nor setting diffuse colors to `r g b <value less than 1.0>` appears to produce colored, translucent (i.e., not textured) mesh surfaces with GLTF 2.0 exporting and no arguments other than -i, -o, and -b. Adding some debug print statements shows that the /GLTF/... code to handle the `material->value->transparency` extracted from the input COLLADA effect transparency values doesn't even run unless you add the --glsl argument; unfortunately, several viewers appear to not support `KHR_technique_webgl`. Is there something simple I should be doing, either in my COLLADA files or in the arguments I give to COLLADA2GLTF, to get simple, Lambertian translucent surfaces? Thanks in advance, and apologies again if this is the wrong place!

**Comment by lasalvavida** [comment]
Hi @KermMartian, converter does not currently handle transparency.

It's the next thing on my list after #206 and https://github.com/KhronosGroup/OpenCOLLADA/pull/592 wrap up.

**Comment by KermMartian** [comment]
@lasalvavida, thanks, I appreciate that! I'm looking at windows specifically; if I can't have transparency at the moment, can I at least implement reflection/reflectivity? Thanks in advance!

**Comment by lasalvavida** [comment]
> can I at least implement reflection/reflectivity

That would be great! I will say it's not super clear to me how to map these COLLADA properties to PBR metallic/roughness + spec/gloss.

Also by the looks of things, OpenCOLLADA only supports parsing the reflectivity effect property. There is some support for Maya export of reflections, but the parser doesn't appear to support reading them, so that would probably be the place to start.

**Comment by lasalvavida** [comment]
Done in #218.
