### ISSUE TITLE
Segmentation Fault for some files

### ISSUE THREAD

**Issue by GiveMeAnthony** [KhronosGroup/COLLADA2GLTF#17]
When attempting to convert this file, [2D.dae.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/753243/2D.dae.zip), it produces a segmentation fault. This was created in blender and exported. The command line tool seems to work fine for other files, but not this one.

_macOS Sierra 10.12.2_
_Blender 2.78 (2016-10-24)_

**Comment by lasalvavida** [comment]
This is likely related to #25.

**Comment by lasalvavida** [comment]
#25 fixes part of this, where a mesh had an unbound material; there is an additional issue where treeArm_leaves-skin isn't getting its jointNames assigned

**Comment by lasalvavida** [comment]
A skin controller is declared in your COLLADA, but it is never instanced; I'll have a fix along for that shortly

**Comment by lasalvavida** [comment]
With #17, this converts correctly: 
[2D.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/817247/2D.zip)
