### ISSUE TITLE
HOW TO CONVERT COLLADA TO JSON FILE FORMAT FOR 3D MODELS

### ISSUE THREAD

**Issue by jasvinder1698** [KhronosGroup/COLLADA2GLTF#173]
I am trying to display 3d models on webGL based application Cesium using the function Cesium3DTileset.
The function requires the file to be in json format. I have tried converting the collada file to json but apparently no online converter seems to work. Can anyone tell me how to upload the model onto cesium globe?
Thank You
![capture](https://user-images.githubusercontent.com/21083640/38501536-e2b7f434-3c2a-11e8-9510-9fce8ad12078.PNG)

**Comment by lasalvavida** [comment]
Hi @jasvinder1698. This project is for converting COLLADA files to the glTF format. You can check out the [Cesium 3D Models Tutorial](https://cesiumjs.org/tutorials/3D-Models-Tutorial/) for information on how to use glTF models in Cesium.

However, the function you linked is for loading a 3D tileset, which is more of a collection of 3D models and is out of the scope of what this project does. 

If you're looking for information on building 3D tilesets, you should go check out the [3d-tiles](https://github.com/AnalyticalGraphicsInc/3d-tiles).

**Comment by emackey** [comment]
@jasvinder1698 Please try asking your question on the [Cesium forums](https://groups.google.com/forum/#!forum/cesium-dev).  This issue tracker is meant for bug & feature requests of the COLLADA2GLTF project.
