### ISSUE TITLE
transparent is always false?

### ISSUE THREAD

**Issue by slozier** [KhronosGroup/COLLADA2GLTF#176]
It seems like `transparent` in `MaterialCommon` is always false. Because of this I can't seem to get transparent materials to work properly.

As a workaround I have to manually edit the gltf file to either update the states of the technique (when using GLSL shaders) or set transparent to true (when using KHR_materials_common).

**Comment by lasalvavida** [comment]
Hi @slozier. I'm going to link this as a todo for @168.

**Comment by lasalvavida** [comment]
Done in #218.
