### ISSUE TITLE
models are showing black in collada to gltf conversion tool window

### ISSUE THREAD

**Issue by unusualujwl** [KhronosGroup/COLLADA2GLTF#177]
i have tried running this tool in 15-20 systems ...got success in only three. the thing which was common in those three systems was there processor that was intel(R) core(TM) i7-3770 
![prob](https://user-images.githubusercontent.com/38319811/38729732-83f33670-3f31-11e8-94d4-d55516238c77.png)

**Comment by emackey** [comment]
Do your models have normal vectors?  We're currently tracking an issue in Cesium where models appear all black if they lack normal vectors.

https://github.com/AnalyticalGraphicsInc/cesium/issues/5838

**Comment by unusualujwl** [comment]
They don't have normal vectors..

**Comment by emackey** [comment]
@unusualujwl Thanks.  This is duplicate with AnalyticalGraphicsInc/cesium#5838 then.  I'm going to close this issue, but you should subscribe to 5838 for updates.
