### ISSUE TITLE
The version of Draco library used in COLLADA2GLTF is old

### ISSUE THREAD

**Issue by cx20** [KhronosGroup/COLLADA2GLTF#178]
I tried compressing [Duck.dae](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/sourceModels/Duck/Duck.dae) with the Draco extension of glTF using the latest version of COLLADA2GLTF below.
https://github.com/KhronosGroup/COLLADA2GLTF/releases/download/v2.1.1/COLLADA2GLTF-v2.1.1-windows-Release-x64.zip

```
collada2gltf-bin -i Duck.dae -o output\Duck.gltf -d -s
```
[Duck_glTF-Draco.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/1934264/Duck_glTF-Draco.zip)

However, the output glTF file could not be displayed due to an error in [Three.js](https://gltf-viewer.donmccurdy.com/) or [Babylon.js](https://sandbox.babylonjs.com/).
Perhaps, the cause seems to be due to the difference in [version](https://google.github.io/draco/spec/) of Draco file.

[Draco file](https://github.com/KhronosGroup/COLLADA2GLTF/files/1934264/Duck_glTF-Draco.zip) output in [COLLADA2GLTF v 2.1.1](https://github.com/KhronosGroup/COLLADA2GLTF/releases/download/v2.1.1/COLLADA2GLTF-v2.1.1-windows-Release-x64.zip).
![image](https://user-images.githubusercontent.com/1833979/39081803-d4105140-4582-11e8-857d-1405e97dea8d.png)

[Draco file](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Duck/glTF-Draco) in the glTF-Sample-Models repository.
![image](https://user-images.githubusercontent.com/1833979/39081815-02fbce3a-4583-11e8-9cee-651774259df3.png)

I think you probably need to update the Draco library.

**Comment by cx20** [comment]
I confirmed using the version of appveyor artifact.
[Duck_glTF-Draco.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/1935196/Duck_glTF-Draco.zip)
I confirmed that it will be displayed without problems with [Three.js](https://gltf-viewer.donmccurdy.com/) and [Babylon.js](https://sandbox.babylonjs.com/).

[Draco file](https://github.com/KhronosGroup/COLLADA2GLTF/files/1935196/Duck_glTF-Draco.zip) output in [COLLADA2GLTF latest version](https://ci.appveyor.com/api/buildjobs/a6q3j6tw5e9uttky/artifacts/cmake-build%2FCOLLADA2GLTF-update-windows-Release-x64.zip)
![image](https://user-images.githubusercontent.com/1833979/39091299-3e94418a-462c-11e8-9229-bc8fe60fc520.png)

Draco's file header seems to have no problem, so I think that this problem is solved.

BTW, I think it's another an existing problem, but with Cesium.js it seems that the Draco compressed skinning model is not displayed properly. For example, [CesiumMan](https://cx20.github.io/gltf-test/examples/cesium/index.html?category=sampleModels&model=CesiumMan&scale=1&type=glTF-Draco) seems not to be displayed. I would like to report this as a separate Issue.

**Comment by lasalvavida** [comment]
Sounds good @cx20, thanks for testing. I pushed out release v2.1.2 with this fix.
