### ISSUE TITLE
Normalize bone weights

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/COLLADA2GLTF#185]
The CesiumMan sample model came through this converter with apparently non-normalized bone weights.  Not sure if COLLADA allows such weights, but it's becoming apparent that glTF does not, and the non-normalized weights are showing up as rendering errors in various frameworks now.

Can this converter normalize these weights automatically?

Spec discussion: https://github.com/KhronosGroup/glTF/issues/1213#issuecomment-385532438

BabylonJS issue: https://github.com/BabylonJS/Babylon.js/issues/4240

Cesium issue: https://github.com/AnalyticalGraphicsInc/cesium/issues/6447

Source COLLADA model: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/sourceModels/CesiumMan

**Comment by lasalvavida** [comment]
Seems like it should be reasonably simple to do. Normalize the weights [here](https://github.com/KhronosGroup/COLLADA2GLTF/blob/master/src/COLLADA2GLTFWriter.cpp#L1619) and this should be resolved.

**Comment by akulagrawal** [comment]
Hi Sir. I am new to open source and interested to work on this issue. Can I take this up?

**Comment by lasalvavida** [comment]
Closed by #187.
