### ISSUE TITLE
Server error with animated example

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/COLLADA2GLTF#188]
A user in the three.js forum provided this DAE example with a simple animated cube:

[cubeTest copy.dae.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/2049768/cubeTest.copy.dae.zip)

On http://52.4.31.236/convertmodel.html it displays an error:

```
500 - Internal server error.
```

I'm not able to test with COLLADA2GLTF locally, unless there's a MacOS release available. Thanks!

**Comment by lasalvavida** [comment]
The COLLADA references a texture not included in the zip. Converts fine locally other than that.

**Comment by donmccurdy** [comment]
Makes sense thanks!
