### ISSUE TITLE
Surface colors not shown correctly while zooming

### ISSUE THREAD

**Issue by Son-HNguyen** [KhronosGroup/COLLADA2GLTF#193]
Hi,

I have a tunnel model in COLLADA and exported it to glTF (v2.0) using the COLLADA2GLTF tool v2.1.2. The glTF file however is not shown correctly (in Cesium and many other visualization tools), namely: 

1. The surface colors (here: red) keep changing in shapes and resolutions while I'm moving or zooming in and out of the model, the nearer the camera is to the model, the better in resolution the colors are displayed (see the far and near view picture below);

    Far view (this image is from a glTF file exported from COLLADA2GLTF v2.1.2):
![image 3](https://user-images.githubusercontent.com/5765503/42681710-c0666070-8688-11e8-9a10-f061a442c3a3.png)

    Near view (this image is from the same glTF file exported from COLLADA2GLTF v2.1.2):
![image 4](https://user-images.githubusercontent.com/5765503/42681715-c4404e40-8688-11e8-84b1-5db4ed3c159f.png)

2. The tunnel mouth should be opened and the interiors of the tunnel should be visible (see picture below):

    How it should be shown (this image is from a glTF file exported from collada2gltf v1.0):
![image 1 1](https://user-images.githubusercontent.com/5765503/42681728-cbc75140-8688-11e8-816e-f64d542a2565.png)

I also attached the source COLLADA and glTF file here in case you need it.

[Model.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/2191943/Model.zip)

Any help or advice is well appreciated.

Thanks!

**Comment by lasalvavida** [comment]
Initially I thought this might be a precision loss issue in the 2.0 converter causing some z-fighting, but the 1.0 model that you attached has the same problem when rendered in the VirtualGIS glTF viewer (uses the Cesium 1.36 engine I believe). Converted it myself with the old converter just to double check and got the same behavior.

![screenshot from 2018-07-13 10 18 18](https://user-images.githubusercontent.com/2489570/42696533-634935ea-8686-11e8-941d-3f3d63de69e8.png)

Then thought maybe it was something with newer Cesium versions upgrading glTF 1.0 -> 2.0, but get the same issue in pre-glTF 2.0 Cesium 1.5.

![screenshot from 2018-07-13 10 41 40](https://user-images.githubusercontent.com/2489570/42697575-7e90257c-8689-11e8-93f2-aeb2fbf1dd66.png)

Finally opened your attached COLLADA model in blender - no z-fighting but the tunnel mouth is not open as you say it should be.

![screenshot from 2018-07-13 10 41 05](https://user-images.githubusercontent.com/2489570/42697696-d28ecebc-8689-11e8-9be6-1759ffacc3dd.png)

Are you sure your COLLADA model did not change?

**Comment by lasalvavida** [comment]
Triangle view for reference:

![screenshot from 2018-07-13 10 51 37](https://user-images.githubusercontent.com/2489570/42698031-c1b6454c-868a-11e8-9e9b-6e70c0ef4fc3.png)

Your COLLADA mesh definitely has closed ends.

**Comment by Son-HNguyen** [comment]
Thanks for the heads up, I just noticed that the COLLADA models used for the glTFs are in fact different:

COLLADA used for the glTF that is shown correctly:
![image](https://user-images.githubusercontent.com/5765503/42701349-a6057cf0-86c6-11e8-98eb-c8cbdb725fd7.png)

COLLADA used for the glTF that is shown incorrectly:
![image](https://user-images.githubusercontent.com/5765503/42701849-ff30e732-86c7-11e8-831f-c7173ba4052c.png)

Does the COLLADA2GLTF Tool v2.1.2 work with COLLADA v1.4?

**Comment by lasalvavida** [comment]
Our COLLADA parsing uses [OpenCOLLADA](https://github.com/KhronosGroup/OpenCOLLADA) which should support v1.4.

Just to be clear, there are no issues with the model produced when you use the correct input model, right?

**Comment by Son-HNguyen** [comment]
Thanks for the reply. I thoroughly checked our COLLADA classes only to find out that the problem was in the input file in the first place. After replacing it with a correct one we were able to produce the correct glTF file. Thanks again for the help!

**Comment by lasalvavida** [comment]
:smile: Glad you got it figured out
