### ISSUE TITLE
No scene is written for some files

### ISSUE THREAD

**Issue by apptaro** [KhronosGroup/COLLADA2GLTF#196]
No scene is written for some collada files as below:
```
>COLLADA2GLTF-bin.exe -i "coco-low-sofa-ottoman.dae" -o "coco-low-sofa-ottoman.gltf" -v 2.0
Converting coco-low-sofa-ottoman.dae -> coco-low-sofa-ottoman.gltf
Time: 3 ms

>type coco-low-sofa-ottoman.gltf
{
    "asset": {
        "generator": "COLLADA2GLTF",
        "version": "2.0"
    },
    "scenes": [
        {
            "nodes": []
        }
    ],
    "scene": 0
}
```
I though empty string id is causing the issue:
```
<?xml version='1.0' encoding='UTF-8'?>
<COLLADA version='1.4.1' xmlns='http://www.collada.org/2005/11/COLLADASchema'>
...
  <library_visual_scenes>
    <visual_scene id='' name=''>
    ..
    </visual_scene>
  </library_visual_scenes>
  <scene>
    <instance_visual_scene url='#'/>
  </scene>
</COLLADA>

```
but fixing it manually in .dae file as below does not resolve the issue:
```
<?xml version='1.0' encoding='UTF-8'?>
<COLLADA version='1.4.1' xmlns='http://www.collada.org/2005/11/COLLADASchema'>
...
  <library_visual_scenes>
    <visual_scene id='vsid' name=''>
    ..
    </visual_scene>
  </library_visual_scenes>
  <scene>
    <instance_visual_scene url='#vsid'/>
  </scene>
</COLLADA>

```

**Comment by apptaro** [comment]
Versions:
- Windows 10 Home
- COLLADA2GLTF-v2.1.2-windows-Release-x64

Here's the Collada data with this issue, exported from Maya:
[data.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/2204483/data.zip)

**Comment by emackey** [comment]
originally via https://github.com/najadojo/gltf-import-export/issues/5

**Comment by lasalvavida** [comment]
I do think the behavior here could be better, but it would have to be fixed in OpenCOLLADA. No error information that I can see is being handed off to COLLADA2GLTF; it just stops calling our writer functions after it chokes on the unidentified parameter.

**Comment by lasalvavida** [comment]
Opened up #197 for the more general issue here, but this one can be closed.

**Comment by emackey** [comment]
@lasalvavida Sounds like the dae file came right out of Maya.  I wonder if that might raise the priority of this for the OpenCOLLADA folks.  Can you file an issue with them?

**Comment by apptaro** [comment]
@lasalvavida Thank you for your response. As you wrote, editing .dae file (move newparam nodes before technique node) fixed the issue. By the way, how did you figure it out without error message? :)

**Comment by lasalvavida** [comment]
Opened https://github.com/KhronosGroup/OpenCOLLADA/issues/584

**Comment by emackey** [comment]
Thanks @lasalvavida
