### ISSUE TITLE
Auto-compile and host binaries (possibly using the Nuts project)

### ISSUE THREAD

**Issue by cvan** [KhronosGroup/COLLADA2GLTF#2]
Consider using the popular desktop-application releases project, [Nuts](https://github.com/GitbookIO/nuts#nuts) by [GitBook](https://github.com/GitbookIO).

There's even a free, one-click [deploy recipe for Heroku](https://github.com/GitbookIO/nuts#nuts).

**Comment by pjcozzi** [comment]
+1, this would be great!

**Comment by lasalvavida** [comment]
I have a rough cut of something like this working on my fork for 2.0: https://github.com/lasalvavida/COLLADA2GLTF. 

Master is automatically built by Travis and Appveyor for CI and on successful build, they update the `latest` tag and put the new compiled binaries there.

**Comment by lasalvavida** [comment]
This is now working here. Releases are generated off of tags. I'm going to close this now.
