### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by dirkse** [KhronosGroup/COLLADA2GLTF#209]
I may be doing something very basic wrong, but when trying to run either the binary downloaded : COLLADA2GLTF-bin
or the built version (see bottom for output), the result is: COLLADA2GLTF-bin: command not found

Any ideas as to what I'm doing wrong?

Thanks,

System is: 
Distributor ID: neon
Description:    KDE neon User Edition 5.13
Release:        16.04
Codename:       xenial

and 

ls -lh /usr/bin/g++
lrwxrwxrwx 1 root root 5 Jan 25  2018 /usr/bin/g++ -> g++-5

 Scanning dependencies of target dracodec
[ 98%] Building CXX object GLTF/dependencies/draco/CMakeFiles/dracodec.dir/__/__/__/draco_version.cc.o
[ 98%] Linking CXX static library libdracodec.a
[ 98%] Built target dracodec
Scanning dependencies of target draco_unity_plugin
[ 99%] Building CXX object GLTF/dependencies/draco/CMakeFiles/draco_unity_plugin.dir/src/draco/unity/draco_unity_plugin.cc.o
[ 99%] Built target draco_unity_plugin
Scanning dependencies of target draco_decoder
[ 99%] Building CXX object GLTF/dependencies/draco/CMakeFiles/draco_decoder.dir/src/draco/tools/draco_decoder.cc.o
[100%] Linking CXX executable draco_decoder
[100%] Built target draco_decoder
theuns@theunsdirksevanschalkwyk-OptiPlex-9010:~/Downloads/COLLADA2GLTF-v2.1.4-linux/COLLADA2GLTF/build$ COLLADA2GLTF-bin
COLLADA2GLTF-bin: command not found
theuns@theunsdirksevanschalkwyk-OptiPlex-9010:~/Downloads/COLLADA2GLTF-v2.1.4-linux/COLLADA2GLTF/build$ ls
CMakeCache.txt  cmake_install.cmake  dependencies                                      DracoConfig.cmake         draco_dec_config.cc  draco.pc          draco_version.h  libCOLLADA2GLTF.a
CMakeFiles      COLLADA2GLTF-bin     draco_compression_attributes_pred_schemes_dec.cc  DracoConfigVersion.cmake  draco_enc_config.cc  draco_version.cc  GLTF             Makefile
theuns@theunsdirksevanschalkwyk-OptiPlex-9010:~/Downloads/COLLADA2GLTF-v2.1.4-linux/COLLADA2GLTF/build$ COLLADA2GLTF-bin
COLLADA2GLTF-bin: command not found

**Comment by lasalvavida** [comment]
On Linux, you typically need a "./" to run local executables. So "./COLLADA2GLTF".

**Comment by lasalvavida** [comment]
@dirkse hope that helped, I'm going to close this since it isn't really a COLLADA2GLTF issue.
