### ISSUE TITLE
SIGBUS in GeneratedSaxParserTemplate.h

### ISSUE THREAD

**Issue by TomJinW** [KhronosGroup/COLLADA2GLTF#214]
When I port this to Android (armeabi-v7a),

I got SIGBUS in line 738

typedBuffer[0] = fragmentData;

Does anyone know why?

**Comment by lasalvavida** [comment]
Hi @TomJinW. This file is part of OpenCOLLADA. I have opened up an [issue](https://github.com/KhronosGroup/OpenCOLLADA/issues/600) for you there.
