### ISSUE TITLE
Cannot run COLLADA2GLTF-bin (or -test) on Ubuntu 16.04 LTS!

### ISSUE THREAD

**Issue by HuyQuoc** [KhronosGroup/COLLADA2GLTF#223]
Hi, 

I'm trying to run COLLADA2GLTF on Ubuntu 16.04 from release version (COLLADA2GLTF-v2.1.4-linux.zip) but I always got "COLLADA2GLTF-bin: cannot execute binary file" error. 

My Ubuntu version have No-GUI. Can u help me to fix it ?

Thanks,
Regards.

**Comment by lasalvavida** [comment]
Probably a permissions thing I would guess.

```bash
sudo chmod +x COLLADA2GLTF-bin
```

This is not a COLLADA2GLTF issue as far as I know.

**Comment by HuyQuoc** [comment]
> Probably a permissions thing I would guess.
> 
> ```shell
> sudo chmod +x COLLADA2GLTF-bin
> ```
> 
> This is not a COLLADA2GLTF issue as far as I know.

Hallo, i already run chmod +x but have nothing different. I dont know exactly why :'(.

**Comment by lasalvavida** [comment]
@HuyQuoc, could you share the output from running this command on your machine?

```bash
uname --m
```
