### ISSUE TITLE
Can the converted GLTF expression be changed?

### ISSUE THREAD

**Issue by liaoweiqi1997** [KhronosGroup/COLLADA2GLTF#232]
I want to change the expression of a GLTF, converts "matrix" to the expression of "rotation, scale and translation".Is the tool currently supported?
![k8x ho8_ 8myw kad6 l8n](https://user-images.githubusercontent.com/31244684/49841423-9051e800-fdf2-11e8-80b7-e6138aeae5d8.png)

**Comment by liaoweiqi1997** [comment]
I see that the output here has a choice, but under what circumstances will the following TRS expression be executed?Are there any parameters you can control?
![0ej8xo a5 3o7 m uy9thx](https://user-images.githubusercontent.com/31244684/49980880-4c94e500-ff90-11e8-8692-4d9a318583dc.png)

**Comment by lasalvavida** [comment]
@liaoweiqi1997, did you mean to close this? Do you understand the answer to your question?

> Q: under what circumstances will the following TRS expression be executed

>> A: the converter should only switch the node transform from matrix form to TRS if it is targeted by an animation

> Q: Are there any parameters you can control

>> A: the only way to express it as a matrix would be to remove the animation

**Comment by liaoweiqi1997** [comment]
修改了源代码，输出改成了只会是rts的表达形式。
