### ISSUE TITLE
Instance Nodes Actually Instanced

### ISSUE THREAD

**Issue by bryantcurto** [KhronosGroup/COLLADA2GLTF#237]
It appears that, in translating from COLLADA to glTF, [instance nodes result in the source node being _cloned_](https://github.com/KhronosGroup/COLLADA2GLTF/blob/master/src/COLLADA2GLTFWriter.cpp#L437-L445).
I wanted to confirm with someone a little more knowledgeable that instance nodes are not being translated by generating multiple unique copies of the node (or something along those lines), but is actually making use of glTF instances defined [here](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#instantiation).

**Comment by lasalvavida** [comment]
@bryantcurto, it's possible that I'm misreading your comment, but I think you might want to re-read the section of the specification that you linked to.

glTF does not possess a concept of instance nodes. The section of the spec that you linked describes creating a mesh instance on a node. Unique nodes must be created in the glTF when properties of a COLLADA instance node are different from the original. Meshes on nodes however are not duplicated when this happens, if that was what you meant.

**Comment by bryantcurto** [comment]
Thanks for your response! I have much more experience with COLLADA than glTF.
>Meshes on nodes however are not duplicated when this happens, if that was what you meant.

This is what I meant.
