### ISSUE TITLE
COLLADA2GLTF-bin converted .glb has duplicate or extra parts

### ISSUE THREAD

**Issue by kunwang1** [KhronosGroup/COLLADA2GLTF#242]
Hi,

I ran the following command to convert a small collada model DMG_DMU50.dae (in the attached zip) to the GLTF binary format (latest version for x64):

collada2gltf-bin DMG_DMU50.dae DMG_DMU50.glb -b

But when I loaded this DMG_DMU50.glb into ThreeJS using the GLTFLoader, the model seemed to be doubled - mirrored itself (attached screenshot wrong-duplicate.png). Then I tried loading the same .glb file with https://blackthread.io/gltf-converter/, the same problem exists there.

Another interesting observation is that, when I drag/drop the original DMG_DMU50.dae into Cesium's web application: http://52.4.31.236/convertmodel.html, the model is displayed correctly, i.e., no duplicate or mirrored parts. Further, if I load the output .glb from this web app with either GLTFLoader or blackthread converter, it's also working properly. So it looks like the DMG_DMU50.glb I generated using the command line is incorrect.

What is the right command (with options) should I use? Why is the .glb output from Cesium's web application correct, as it is using the same converter as I do?

Attached please find the screenshots, original .dae and the converted .glb from the command line. Thank you in advance for any help!

-Kun

[files.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/2958967/files.zip)

**Comment by kunwang1** [comment]
Hi, 

I just checked a few older versions, starting from v1.0.0. The last one that works for me (no duplicate) is v2.0.0. This duplicate issue seems to be a regression since that version.

Thanks,

-Kun

**Comment by lasalvavida** [comment]
Hi @kunwang1, this will be fixed by #239.

**Comment by kunwang1** [comment]
Hello Rob, this is good to know. When can I expect a new version with this fix?

Thank you,

-Kun

**Comment by lasalvavida** [comment]
Fixed in #239.

> When can I expect a new version with this fix?

We're definitely overdue for a minor release. I don't want to make any promises because my schedule has been kind of crazy, but that will be the next thing I make time to do.

For now, you can certainly build from master yourself or if you're on windows, you can download build artifacts from any of the [appveyor jobs](https://ci.appveyor.com/project/Khronoswebmaster/collada2gltf/history).

I will comment here once a new release is pushed out.

**Comment by kunwang1** [comment]
Hi Rob, 
I downloaded the built artifact for Windows 64 and tried it - worked! Thank you so much, and it's awesome!!
-Kun

    On Thursday, March 14, 2019, 8:38:51 a.m. EDT, Rob Taglang <notifications@github.com> wrote:  
 
 
Fixed in #239.


When can I expect a new version with this fix?


We're definitely overdue for a minor release. I don't want to make any promises because my schedule has been kind of crazy, but that will be the next thing I make time to do.

For now, you can certainly build from master yourself or if you're on windows, you can download build artifacts from any of the appveyor jobs.

I will comment here once a new release is pushed out.
