### ISSUE TITLE
.DAE file that references images with space in filename are incorrectly mapped

### ISSUE THREAD

**Issue by roxlu** [KhronosGroup/COLLADA2GLTF#243]
When I convert a .dae file with an `image` tag that has an `init_from` tag with a file uri that contains a space, the generated gltf file will have an image with an uri with only the filename up to the first space. 
e.g.

```
<image id="_NC_RAL-9010.jpg" name="_NC_RAL-9010.jpg">
	<init_from>./RAL 9010.jpg</init_from>
</image>
```

Results in an image object like:

```
{
    "uri": "RAL"
},
```
This should be the same filename. 

Is the collada file I'm using incorrect or is this an issue with the converter?

**Comment by lasalvavida** [comment]
Uris can't have spaces. They need to be encoded as %20. Where did this model come from?

**Comment by roxlu** [comment]
Ah, thanks @lasalvavida. The collada file is exported from proprietary software.
