### ISSUE TITLE
请问如何将 dae 转换成 有透明材质的gltf文件

### ISSUE THREAD

**Issue by HuZhuangQiang** [KhronosGroup/COLLADA2GLTF#246]
使用 collada2gltf 转换dae 模型，但是转换后没有透明材质，请问有什么方法或工具转换？
   我知道obj2gltf 中有--checkTransparency 选项可以使其材质透明，那collada2gltf 有什么办法或工具可以做出同样的效果。
尾焰效果：
   最终想 实现的效果：
![捕获1](https://user-images.githubusercontent.com/33933148/56638648-441c8b80-66a1-11e9-9c1b-e6299ae64bdd.PNG)

   目前使用collada2gltf 转出的效果图：
![捕获](https://user-images.githubusercontent.com/33933148/56638676-60b8c380-66a1-11e9-93bc-32461b64ffb4.PNG)

**Comment by lasalvavida** [comment]
Hi @HuZhuangQiang, could you please attach your COLLADA model so I can take a look?

**Comment by HuZhuangQiang** [comment]
@lasalvavida ,
使用工具
     COLLADA2GLTF-v2.1.4-windows-Release-x64 

文件
[flame.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/3115357/flame.zip)

**Comment by lasalvavida** [comment]
Hi @HuZhuangQiang, this is currently expected, you can read my summary at #121 for more information.

In short, glTF doesn't have a direct equivalent for COLLADA `transparent` maps, and the image processing required to do this is not on the roadmap currently.

**Comment by emackey** [comment]
I don't know about COLLADA's `transparent` maps, but for what it's worth, glTF can do the effect shown in the screenshots above.

* Put the flame RGB image in the `emissiveTexture` channel.
* Put a black image with flame alpha channel in the `baseColorTexture` channel (such that the base color is pure black, but the alpha channel holds the shape of the flame).
* Set `"alphaMode" : "BLEND"` and `"doubleSided" : true`

Like so:

[flame-glTF.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/3118328/flame-glTF.zip)

**Comment by lasalvavida** [comment]
This is true, but as I said above, the image processing required do that automatically is not something that is currently planned.

You could certainly modify the source COLLADA + textures as described to get the desired effect.
