### ISSUE TITLE
crashes when same geometry is instanced twice with different material

### ISSUE THREAD

**Issue by RemiArnaud** [KhronosGroup/COLLADA2GLTF#25]
[build_boat_dragonhead_01.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/791966/build_boat_dragonhead_01.zip)

**Comment by RemiArnaud** [comment]
I created a work around branch which avoids the crash, but does not fix the issue.

https://github.com/StarbreezeStudios/COLLADA2GLTF/tree/misc/work-around

this output a gltf file that has two instances of the same mesh in the scene. But two different meshes are created, but one point so a empty material.

[build_boat_dragonhead_01.gltf.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/792018/build_boat_dragonhead_01.gltf.zip)

**Comment by lasalvavida** [comment]
@RemiArnaud thank you for bringing this to my attention

**Comment by lasalvavida** [comment]
This should be fixed by #27: 
[dragonhead.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/817125/dragonhead.zip)

**Comment by RemiArnaud** [comment]
checked with master build
