### ISSUE TITLE
duplicate materials

### ISSUE THREAD

**Issue by loadpixels** [KhronosGroup/COLLADA2GLTF#251]
When converting a file I'm getting an input .dae with ~21 materials converted to ~169 materials. It appears that the converter creates a new identical material for every object it finds in the scene rather than just assigning an existing one to the object.

Obviously this has problems for further down the pipeline where reducing drawcalls by limiting materials is desirable.

**Comment by lasalvavida** [comment]
Hi @loadpixels. I would need to see the source model to say anything definitively, but the converter does not create a new identical material for every object in the scene.

I suspect what you are seeing is COLLADA instance materials with different overriden properties being split out as new materials in glTF, which is expected and unavoidable.

Feel free to attach your model if you'd like me to take a closer look.

**Comment by loadpixels** [comment]
Hi @lasalvavida - please find attached the original and the converted file. You can see multiple materials with the exact same properties, which I would have imagined would generally be best collapsed down to a single material. I don't believe that the geometry has any attributes that would affect the different materials, but perhaps I'm wrong.

Is this in anyway related to pull request #100 ?

[test dae and gltf.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/3325471/test.dae.and.gltf.zip)

**Comment by lasalvavida** [comment]
Definitely something strange going on here. As far as I can tell, it looks like something may be tripping up OpenCOLLADA. There are some elements here that have the same id in the COLLADA, which isn't valid, they need to be unique within the document. For example, there are a bunch of nodes with the id "IfcWindow". Will look into this a bit closer later.

**Comment by loadpixels** [comment]
Thanks for looking at this, I've tried reexporting the DAE (using https://github.com/IfcOpenBot/IfcOpenShell) to enforce GUIDs on every element, but I still appear to get the same issue.

Test files attached

[test ifc dae gltf.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/3325968/test.ifc.dae.gltf.zip)

**Comment by KermMartian** [comment]
I'm able to replicate this. I have a single COLLADA material set to two pieces of geometry, each of which has unique `id`s and `name`s, and two identical GLTF materials are being created, each with the same `name` field. Let me know if there's anything I can provide to assist.

**Comment by lasalvavida** [comment]
Hi @KermMartian, if you could attach the model, that would be much appreciated. More data always helps.

**Comment by KermMartian** [comment]
Please find attached a sample model in DAE and GLB format. If I'm counting correctly:

DAE:
- 2 images
- 6 effects
- 6 materials
- 12 meshes
- 8 nodes in node library
- 125  `instance_node`s or `instance_geometry`s

GLTF:
- 4 textures
- 12 materials
- 12 meshes
- 12 primitives
- 165 nodes

[struct.dae.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/3693870/struct.dae.zip)

**Comment by KermMartian** [comment]
*bump* Anything I can do to further assist with this?

**Comment by freeinform** [comment]
Same problem, materials are duplicated.

**Comment by KermMartian** [comment]
*bumpity bump* Anything I can do to help with this? It's a serious problem for us.

**Comment by lasalvavida** [comment]
Fixed in #266
