### ISSUE TITLE
add flag for not storing path references in .gltf

### ISSUE THREAD

**Issue by feiss** [KhronosGroup/COLLADA2GLTF#26]
using collada2gltf@cf6371beb0bdc18ba603378d5e40c966da53d385

When using the converter from a folder different than the path specified in the `-o` parameter, the path reference is stored with the files. For example, in this scenario:

```
/current folder
  /input
  /output
```

If you do:

`collada2gltf -f input/asset.dae -o output/asset`

will generate both  `output/asset.gltf` and `output/asset.bin`. In the `asset.gltf` the reference to the asset file is:
```json
"buffers": {
  "output/asset": {
    "byteLength": 999,
    "type": "arraybuffer",
    "uri": "output/asset.bin"
  }
}
```

The "common" use case is to have the `.bin` file in the same folder as the `.gltf` file, so you normally want this file references free of any path. 

i.e., the output should be *always* like this:

```json
"buffers": {
  "asset": {
    "byteLength": 999,
    "type": "arraybuffer",
    "uri": "asset.bin"
  }
}
```

But I guess the current behaviour is also desired for some. So what about adding a flag? something like:
`-ol -> remove all paths in file references`

**Comment by jcuda** [comment]
Related https://github.com/KhronosGroup/glTF/issues/286

**Comment by javagl** [comment]
Related https://github.com/KhronosGroup/glTF/issues/286

**Comment by lasalvavida** [comment]
Closing. This isn't an issue in the new converter as far as I'm aware.
