### ISSUE TITLE
fatal error: draco/draco_features.h: No such file or directory when make?

### ISSUE THREAD

**Issue by hxboxy-xh** [KhronosGroup/COLLADA2GLTF#289]
mkdir build
cd build
cmake ../
make

show fatal error: draco/draco_features.h: No such file or directory 

but this is in build/draco folder , i dont know why/

and just only build draco in follow draco readme in draco folder, the draco can build success.

**Comment by javagl** [comment]
Where exactly is your `draco` folder, or how did you clone this repository?

When you clone it with

    git clone git@github.com:KhronosGroup/COLLADA2GLTF.git --recurse-submodules

(note the `--recurse-submodules` part!), then it should put draco into the 

    COLLADA2GLTF/GLTF/dependencies/draco

folder. (Note that this is in the `GLTF/dependencies` _sub_folder, and not in the `COLLADA2GLTF/dependencies` folder)

**Comment by hxboxy-xh** [comment]
@javagl  yes, the draco is in COLLADA2GLTF/GLTF/dependencies/, not _COLLADA2GLTF/dependencies_

when cmake ../,  the draco_features.h in **build/draco** folder
and then when make, show : fatal error: draco/draco_features.h: No such file or directory

**Comment by hxboxy-xh** [comment]
@javagl 
i am not clone the source code with “git clone git@github.com:KhronosGroup/COLLADA2GLTF.git --recurse-submodules“
i just download the the code in https://github.com/KhronosGroup/COLLADA2GLTF/archive/refs/tags/v2.1.5.zip
and other submodules in there release， and put then to the right folder:
ahoy in COLLADA2GLTF/dependencies
OpenCOLLADA in COLLADA2GLTF/dependencies/OpenCOLLADA

draco in GLTF/dependencies

**Comment by hxboxy-xh** [comment]
draco 1.4.3  has this problem
 1.2.5 is ok

**Comment by javagl** [comment]
The advantage of using `git clone ... --recurse-submodules` here is that it will check out Draco _with the exact version that is required_ . So you don't have to manually download different source code ZIP files and make sure that the versions are compatible. 

If it does work with Draco 1.2.5, then feel free to close this issue.
