### ISSUE TITLE
Converting GLTF to Collada?

### ISSUE THREAD

**Issue by vovchykbratyk** [KhronosGroup/COLLADA2GLTF#296]
Probably an enhancement request - but does Khronos have a best practice for converting from GLTF/GLB to Collada?

**Comment by javagl** [comment]
A common way should be to load the model e.g. in Blender, and export it as COLLADA from there. But it's an unusal task in many ways, so I doubt there is a _dedicated_ command line tool for that. (One could probably build something similar to https://github.com/KhronosGroup/glTF-Tutorials/tree/master/BlenderGltfConverter ...)

**Comment by vovchykbratyk** [comment]
Thanks. That's what I'm doing currently.  Understand it's an edge case, and what I was planning on doing is using the Blender python API to script it out.  Just wasn't sure if there was a more dedicated solution.
