### ISSUE TITLE
glTF 2.0 support

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/COLLADA2GLTF#3]
Since glTF 1.1 is incompatible with 1.0, converter should support only newer version or provide a way to specify desired format.

**Comment by lexaknyazev** [comment]
glTF 1.1 changes: https://github.com/KhronosGroup/glTF/issues/605

**Comment by lasalvavida** [comment]
@lexaknyazev to keep you in the loop these changes will be part of a larger scale refactoring based out of: https://github.com/lasalvavida/COLLADA2GLTF/tree/converter1.1

**Comment by lasalvavida** [comment]
The 2.0 converter can now be found here: https://github.com/KhronosGroup/COLLADA2GLTF/tree/2.0

**Comment by pjcozzi** [comment]
@lasalvavida please open a pull request when you are ready (with a task list of any any remaining work) and we'll ask the community to help test it.  I know @lilleyse has been preparing test data.

**Comment by emackey** [comment]
Here are some things I've found with the current work-in-progress on the 2.0 branch:

- [ ] `emissiveTexture` is not supported.
- [ ] `emissiveFactor` defaults to all zeros in the draft spec, and will thus completely suppress any provided `emissiveTexture` by multiplying each texel by zero.  The converter could work around this by setting `emissiveFactor` to `(1,1,1)` when any `emissiveTexture` is present.
- [ ] When writing `textures`, the converter still outputs `format`, `internalFormat`, `target`, and `type`, which are all removed from 2.0.
- [ ] In one test model with two materials, it appeared the converter assigned the base color map from the first input material to both output materials, and maybe dropped the normal map from the second input material.  I haven't dug further but I can produce a reduced COLLADA test file if one is needed for investigating this.
- [ ] Multiple UV maps are not supported.  This would be nice but I'm not sure how widely supported this will be.  It looks like BabylonJS can handle two UV maps in its shaders.
- [ ] Would be great to have a commandline flag to treat COLLADA's ambient texture as both `occlusionTexture` and `metallicRoughnessTexture`, using the same texture index for both.  The 2.0 spec allows for reading occlusion from R and rough/metal from G/B of the same map.

**Comment by pjcozzi** [comment]
Thanks for testing this out, @emackey!  All good input.

>  Multiple UV maps are not supported. This would be nice but I'm not sure how widely supported this will be. It looks like BabylonJS can handle two UV maps in its shaders.

I would be fine with creating a new issue for this to help get this PR merged faster.

**Comment by lasalvavida** [comment]
@emackey, I've addressed most of your feedback except for multiple UV maps. #37 has been opened to merge 2.0 into master.

**Comment by lasalvavida** [comment]
Closed by #37.
