### ISSUE TITLE
Collada2Gltf seems to ignore translations in animation?

### ISSUE THREAD

**Issue by likangning93** [KhronosGroup/COLLADA2GLTF#32]
I have a blender animation that has joint translations. When I export it to collada and send it through collada2gltf, it seems like all the translations get ignored.

Here's how it looks in blender:
![cesium man go blender](https://cloud.githubusercontent.com/assets/5395255/24086166/fe6da892-0ce0-11e7-869d-70f2391a4147.gif)

And here's how it looks in Sandcastle:
![cesium man go gltf](https://cloud.githubusercontent.com/assets/5395255/24086167/060f8d04-0ce1-11e7-86e6-c795b2ae8efa.gif)

Note that Cesium Man's hips don't move up and down in the gltf version. I tried parenting the animation skeleton to a "scene" bone in case collada2gltf was just ignoring the root transformations, but that didn't seem to fix the problem. I've also tried re-importing the collada to blender in case it was a problem with blender's exporter, but that seems to be just fine.

I've attached the collada file and output embedded gltf below. I can also provide blender files if needed.

[CesiumManGo.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/853705/CesiumManGo.zip)

**Comment by lasalvavida** [comment]
This is fixed in the latest build of the COLLADA2GLTF-2.0 converter

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/2489570/25295927/c748d610-26b3-11e7-8031-1ff173e17133.gif)

[CesiumManGo.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/948307/CesiumManGo.zip)

**Comment by pjcozzi** [comment]
@likangning93 can you please verify the fix when you have time?

**Comment by lasalvavida** [comment]
@likangning93, for testing you can grab a built binary from [my fork](https://github.com/lasalvavida/COLLADA2GLTF/releases) under *latest*. And test with the [gltf-2](https://github.com/lasalvavida/cesium/tree/gltf-1.1) of cesium.

**Comment by lasalvavida** [comment]
I am going to close this since the issue has been resolved.
