### ISSUE TITLE
Enable Travis and Appveyor builds

### ISSUE THREAD

**Issue by lasalvavida** [KhronosGroup/COLLADA2GLTF#33]
@pjcozzi, there are now valid configurations for Travis and Appveyor on this repo, we just need to flip the switch. This is done by signing into travis-ci.org with an account that has admin access to this repo and enabling it for CI. Then, sign into ci.appveyor.com and create a new project for this repo. After that, CI should automatically build for windows and linux on the next commit.

**Comment by pjcozzi** [comment]
@outofcontrol could you please follow the above instructions so we can have CI (e.g., automated builds) for this repo?  Thanks!

**Comment by Khronoswebmaster** [comment]
Both Travis and Appveyor are enable. Badges are:

    [![Build Status](https://travis-ci.org/KhronosGroup/COLLADA2GLTF.svg?branch=master)](https://travis-ci.org/KhronosGroup/COLLADA2GLTF)   

--

    [![Build status](https://ci.appveyor.com/api/projects/status/3xtpxjohflwd5t1p?svg=true)](https://ci.appveyor.com/project/Khronoswebmaster/collada2gltf)

**Comment by pjcozzi** [comment]
Nice, thanks @lasalvavida @Khronoswebmaster!

@lasalvavida can you please do final testing and add the badges to README.md?

**Comment by lasalvavida** [comment]
@Khronoswebmaster, this should be the last thing. The encrypted tokens in the config currently are set up for my credentials; they should be regenerated by the owner of the repo.

I've put up some instructions for this process on the [wiki](https://github.com/KhronosGroup/COLLADA2GLTF/wiki/Continuous-Integration). These will also be helpful for people who want to set up CI on their own forks.

I would appreciate it if you could follow those instructions to update the configs and let me know if you have any issues

**Comment by outofcontrol** [comment]
What am I missing here? None of the other repos we have using Travis us tokens. Why does this repo need tokens?

**Comment by lasalvavida** [comment]
For deployment to GitHub releases and updating the `latest` tag on successful build

**Comment by outofcontrol** [comment]
The other repos are deploying builds without tokens. When we link travis with our repos, we already give permission to have write access. I'll look into this further and see what's needed here.

**Comment by lasalvavida** [comment]
Of course, do whatever you need to for verification. I did just do a quick survey of some of the other Khronos repos with Travis configs and none of the ones I saw were using the [Travis deployment](https://docs.travis-ci.com/user/deployment/releases/) feature, so it looks like they are doing their releases manually.

**Comment by outofcontrol** [comment]
The following are using Travis. Some appear to push the build to the repository. I'm not sure if they update the latest tag. Not trying to be difficult here, just trying to understand the process so we can get this repo setup in the best manner. 

KhronosGroup/glslang
KhronosGroup/SPIRV-Cross
KhronosGroup/SPIRV-Tools
KhronosGroup/Vulkan-LoaderAndValidationLayers
KhronosGroup/WebGL
KhronosGroup/Vulkan-Samples
KhronosGroup/Vulkan-Hpp
KhronosGroup/SPIRV-LLVM
KhronosGroup/KTX

**Comment by lasalvavida** [comment]
Which ones do you see pushing builds? I just looked at the repos you listed and I don't see that in any of their configs.

**Comment by pjcozzi** [comment]
@outofcontrol is this a permissions issue?

**Comment by outofcontrol** [comment]
@lasalvavida is correct, we just need to update the tokens to be not using his. I've not gotten to it yet.

**Comment by lasalvavida** [comment]
@outofcontrol, any idea when you'll be able to take a look at this?

**Comment by outofcontrol** [comment]
PR just submitted. Let me know if I did things correctly. You might want to update your wiki page by removing --add from the first token generation. At least on macOS automatically adding the token with `travis encrypt` really messes up the line breaks in the `.travis.yml` file. Suggest manually adding the new token.

**Comment by lasalvavida** [comment]
Noted and updated

**Comment by lasalvavida** [comment]
Updating the latest tag doesn't seem to work, but I checked my fork and it looks like its broken there as well. Maybe github changed their api permissions, but it was kind of clunky anyway, so I've removed it. If you generated a second `GH_TOKEN` key, you can remove it, as it won't be used.

**Comment by lasalvavida** [comment]
@outofcontrol, travis deployment looks fine, but appveyor is erroring out with a `401 - Unauthorized`, could you double check the encrypted key?

**Comment by outofcontrol** [comment]
Verified that key is correct when generated from the public_repo token.

**Comment by lasalvavida** [comment]
Looks like it's working now, thanks @outofcontrol. I'm going to close this.

**Comment by pjcozzi** [comment]
This is great, thanks @lasalvavida @outofcontrol!
