### ISSUE TITLE
geolocalisation

### ISSUE THREAD

**Issue by insmdl00** [KhronosGroup/COLLADA2GLTF#35]
Hello,
I am trying to convert from collada to gltf using the tool COLLADA2GLTF.
However, I need to preserve the latitude and longitude information in the converted file (I think I should use CESIUM_RTC tag of Cesium). Can I do it with the tool? If i can, how can I do it. I have been trying for long time but I had no success.

Thank you very much for your reply and help.
Regards
Martin.

**Comment by pjcozzi** [comment]
Martin - glTF doesn't have longitude and latitude.  You might want to store this a glTF `extras` object property, but this is not already in COLLADA2GLTF.

**Comment by lasalvavida** [comment]
@insmdl00, are you saying that the COLLADA file has latitude and longitude? Could you attach your model here so we can assess?

**Comment by lasalvavida** [comment]
@insmdl00, I am going to close this due to inactivity. Feel free to reopen it if this is still a concern.
