### ISSUE TITLE
What is the status of ktx format texture support in branch 2.0 ?

### ISSUE THREAD

**Issue by linuxaged** [KhronosGroup/COLLADA2GLTF#36]
It seems only jpg, png, gif are support.    https://github.com/KhronosGroup/COLLADA2GLTF/blob/86001551e098fbb15e730607588efc2fc68ea93d/COLLADA2GLTFWriter.cpp#L1380-L1391

**Comment by pjcozzi** [comment]
I don't believe it is implemented; KTX will not be part of glTF 2.0: https://github.com/KhronosGroup/glTF/issues/835#issuecomment-292038169

**Comment by lasalvavida** [comment]
It is true that KTX is not supported in glTF, but it is supported in COLLADA. If possible, we should convert these textures. I am closing this issue in favor of #73.
