### ISSUE TITLE
unsupported opaque mode:RGB_ZERO fallback to A_ONE

### ISSUE THREAD

**Issue by anilergin** [KhronosGroup/COLLADA2GLTF#38]
Hello,

When I try to convert .dae files to gltf, I get "unsupported opaque mode:RGB_ZERO fallback to A_ONE"

Is there any solution for this? We get the same error for all our models. This is very critical for us. We have to solve this problem as soon as possible.

Thanks for help.

**Comment by pjcozzi** [comment]
@tfili do you recall if there is a workaround here?

**Comment by tfili** [comment]
A lot of models we ran into didn't even use transparency, so in most cases we could just remove the `RBG_ZERO` opaque mode. As far as I know, the only workaround would be to change the material in the source model to be A_ONE. Gltf materials that are generated don't have the transparent color `RGB_ZERO` needs, so adding it would mean it would have to be added to a bunch places.

**Comment by anilergin** [comment]
So in this case the model makers should intervene? Or can I produce .gltf files by modifying something with the .dae files I have? Or by changing the COLLADA2GLTF conversion files? I do not know much about 3d modeling. Actually, the subject is: What do I have to say to friends who do this? Could you write that sentence? Thank you. @tfili

**Comment by anilergin** [comment]
Somebody help? What I need to fix it?

How do I speak to the team? Is it like this? "remove RGB_ZERO" 
Is it right?

Tjhanks.

**Comment by liduanyang** [comment]
@anilergin did you solved the problem?could you share the method with me? I have encountered same question with you, the dae file is converted from Bentley dgn file (Modeling tool was Bentley AECOsim building designer, and the model was build several months ago, the workspace of AECOsim has been changed recently ), when I try to convert the dae to gltf by collada2gltf tool, same warning with you :unsupported opaque mode:RGB_ZERO fallback to A_ONE. I wander if there is some workaround to repire the dae file, orelse all the model I built before is useless... thank you all!

**Comment by lasalvavida** [comment]
Closing; this isn't relevant in the new converter. Any transparency issues will be handled as part of #168.
