### ISSUE TITLE
Non-deterministic accessor ordering

### ISSUE THREAD

**Issue by lasalvavida** [KhronosGroup/COLLADA2GLTF#49]
Currently `getAllAccessors` uses `std::set` to avoid duplicates when traversing. Unfortunately this creates a non-deterministic accessor ordering, which is a bit of an issue for glTF-Sample-Models, since it means that the buffer for a regeneration of a sample model may change because of re-ordering even though the data itself didn't change. This should be fixed to help keep bloat to a minimum.

**Comment by javagl** [comment]
A side note (from a non-C++-expert) : Actually, a `std::set` **is** ordered. The reason of why it appears to be non-ordered is that it stores `Accessor*` (pointer) objects. These are ascending referring to the *address*, but of course, the addresses here are arbitrary. (Nevertheless, the actual point that [`getAllAccessors`](https://github.com/KhronosGroup/COLLADA2GLTF/blob/40de76bfc722c2b62a8601461cf22ed05fc6502c/GLTF/src/GLTFAsset.cpp#L48) may not return a `std::set` still applies - regardless of how this will be solved exactly)

**Comment by lasalvavida** [comment]
@javagl, yes that is correct. I suspect that overloading the comparison operator for `Accessor` to compare on byteOffset and bufferView byteStride will probably be a sufficient.

**Comment by pjcozzi** [comment]
OK to close this via #50?
