### ISSUE TITLE
Cannot build latest sources due to missing CMakeLists for OpenCollada dependency

### ISSUE THREAD

**Issue by sbtron** [KhronosGroup/COLLADA2GLTF#5]
It looks like the OpenCollada dependencies were not moved from the old repo to this one. 
CMake errors out when it cannot find the CMakeLists file for OpenCollada.

I was able to work around it and run CMake by using the files I had lying around in an old fork: 
https://github.com/KhronosGroup/OpenCOLLADA/tree/fedad28dcd23282d4f0ffc78f2cba14ea6ab9744

Not sure if these files were just missing or explicitly removed when moving the repo?

**Comment by javagl** [comment]
It is linked in as a git submodule. Did you use

    git clone --recursive https://github.com/KhronosGroup/COLLADA2GLTF.git
              ^^^this?^^^

Otherwise, you may use

    git submodule update --init --recursive

in the COLLADA2GLTF directory (or maybe in the */dependencies* subdirectory, I didn't try this out) according to http://stackoverflow.com/a/4438292/

**Comment by sbtron** [comment]
Thanks! I missed that.
The submodule update works and is useful if you missed the the recursive when cloning.

**Comment by javagl** [comment]
Maybe this should be mentioned in the README? Possibly together with some information about libpng - it complained that this was missing last time when I tried it. (If desired, I'd add some "Build instructions" to the README and open a PR, but can't do this in the next few days...)

**Comment by lexaknyazev** [comment]
@sbtron @javagl @lasalvavida 
Please review #6.
