### ISSUE TITLE
Set up caching for AppVeyor

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/COLLADA2GLTF#54]
Each AppVeyor build takes about 30 minutes. Each PR/commit triggers two of them, so we have to wait ~1 hour before merging. Most of that time is being spent inside OpenCOLLADA sources.

@lasalvavida 
Is it possible to cache dependencies to not build them each time from scratch?

**Comment by lasalvavida** [comment]
We actually already do this, see:
```
cache:
- cmake-build/dependencies -> appveyor.yml, .gitmodules
- cmake-build/GLTF/dependencies -> appveyor.yml, .gitmodules
```

This is a problem that needs fixing, but it is probably a visual studio configuration problem, since the files are cached.

**Comment by lasalvavida** [comment]
Also, a note for reference, travis doesn't support automatic cache invalidation like AppVeyor does, so if the cache breaks the build, it has to be cleared manually; not ideal.

Downloading built binaries externally would definitely help the runtime of both build scripts.

**Comment by RemiArnaud** [comment]
Opencollada binaries are available directly on github in the release tab - https://github.com/KhronosGroup/OpenCOLLADA/releases

I recommend using those because they have been built on a controlled environment, and have the release number burn in by the opencollada build process.

**Comment by lasalvavida** [comment]
@RemiArnaud, I appreciate that; unfortunately the OpenCOLLADA releases don't have built binaries for all of the variants that we build here (x86, x64, Debug, Release). If that were available, I would definitely use them.

For the time being I've parked our built dependencies with variants on a release [here](https://github.com/KhronosGroup/COLLADA2GLTF/releases/tag/dependencies), which may not be such a bad thing in case we eventually have other projects we don't want to build in CI besides OpenCOLLADA, for example for something like #73.

**Comment by lasalvavida** [comment]
Closed by #74.

**Comment by RemiArnaud** [comment]
@lasalvavida - please let me know what you need, we'll build those binaries.

**Comment by lasalvavida** [comment]
@RemiArnaud. Sure! Right now it looks like the windows release you have was built in x64 release mode. That means for windows you are missing x64 debug, x86 release and x86 debug. I haven't tried the Linux and Mac binaries yet.
