### ISSUE TITLE
Binary GLTF

### ISSUE THREAD

**Issue by pasu** [KhronosGroup/COLLADA2GLTF#60]
Hi,
I can not find the argument which can  genera binary gltf format?
Do we support binary format with the “gltf” prefixion？

I want to generate b3dm, it is better if I can get the binary gltf
thanks for your advice

**Comment by lasalvavida** [comment]
Hi @pasu. You can generate binary glTF if you are using the 2.0 branch, but the current master does not support this functionality. 

If you need to generate binary glTF for glTF 1.0, you can use [gltf-pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline) to do that.

**Comment by pasu** [comment]
ok, I got it, thanks :+1:
