### ISSUE TITLE
Can't find XCode Project File

### ISSUE THREAD

**Issue by krsnadjava25** [KhronosGroup/COLLADA2GLTF#61]
The project repository not contain any xcode project file. Was OS X installation steps should be changed?
![screen shot 2017-07-07 at 10 34 00 am](https://user-images.githubusercontent.com/14325185/27942531-d06ec602-6301-11e7-8812-7e00daeb9793.png)

**Comment by pjcozzi** [comment]
Have you tried these instructions: https://github.com/KhronosGroup/COLLADA2GLTF/wiki#mac-osx

**Comment by krsnadjava25** [comment]
Oh, sorry i just read the documentation wrong... (i only read README and it's different with the wiki).
Thanks.
Closing it now

**Comment by pjcozzi** [comment]
No problem, glad you figured it out.
