### ISSUE TITLE
Where is GLTF 2.0 support?

### ISSUE THREAD

**Issue by Reon90** [KhronosGroup/COLLADA2GLTF#62]
I built branch 2.0, but when I tried to convert different models they used GLTF 1.0.
What am I do wrong?

**Comment by pjcozzi** [comment]
@Reon90 this work is still in progress.  If you have the bandwidth, you are very welcome to contribute.

**Comment by emackey** [comment]
Definitely still a work in progress.  That said though, if you built and used the 2.0 branch, you should see a 2.0 model come out of it, not glTF 1.0.  Support for 1.0 was dropped from the 2.0 branch.

**Comment by lasalvavida** [comment]
@Reon90, did you figure this out? The 2.0 branch should definitely only produce glTF 2.0 models.

**Comment by RemiArnaud** [comment]
2.0 branch writes   "version": "1.0.1" in the gltf

**Comment by pjcozzi** [comment]
@lasalvavida do you know if the 2.0 branch is just still writing "1.0.1" as an oversight or is there another branch @RemiArnaud should be looking at?

**Comment by RemiArnaud** [comment]
no, I took this back. It was an older version of the branch.. sorry

**Comment by emackey** [comment]
:+1:  Sounds like it's safe to close this.

**Comment by lasalvavida** [comment]
Thanks @emackey!
