### ISSUE TITLE
uri for bin and shader is wrong when using paths 

### ISSUE THREAD

**Issue by RemiArnaud** [KhronosGroup/COLLADA2GLTF#63]
on windows. here's an example:

>F:/unit-test/2017-1/Assets\Editor\Collada\pcbin\collada2gltf.exe -r -f C:/Users/remi/Desktop/tests/prop_barrel_01.dae -o C:\Users\remi\Desktop\tests\prop_barrel_01.gltf

this results in:
"buffer": "\\Users\\remi\\Desktop\\tests\\prop_barrel_01",

and

"shaders": {
        "\\Users\\remi\\Desktop\\tests\\prop_barrel_010FS": {
            "type": 35632,
            "uri": "\\Users\\remi\\Desktop\\tests\\prop_barrel_010FS.glsl"

only the images are correct
    "images": {
        "_2be69b1584d71e048a393fff2ef0a80d": {
            "name": "prop_barrel_01_sg",
            "uri": "textures/Textures/Props/prop_barrel_01_sg.png"

**Comment by javagl** [comment]
Related https://github.com/KhronosGroup/COLLADA2GLTF/issues/26 (and the one linked from there, and several others ... in fact, this is a long-standing issue)

**Comment by RemiArnaud** [comment]
Yes it is.  
The additional take here is the code used for image, where the URI  is provided as UID at its creation, and using a uri object to write out works. 
So, the solution would probably be to copy/paste the image code for all other objects using external references. Maybe have a parent object and derive from it ...

**Comment by lasalvavida** [comment]
Closing. This isn't an issue in the new converter as far as I'm aware.
