### ISSUE TITLE
Normal Maps are Not Working

### ISSUE THREAD

**Issue by davidpro** [KhronosGroup/COLLADA2GLTF#67]
### Normal Maps are Not Working:

[GLTF2NormalMapsTest.zip](https://github.com/KhronosGroup/glTF/files/1202901/GLTF2NormalMapsTest.zip)

* Maya 2014 x64
* Plugin For Export from Maya to Collada [COLLADA-MAYA-PC-2014 v1.6.58](https://github.com/KhronosGroup/OpenCOLLADA/releases)
* Collada2Gltf [COLLADA2GLTF-2.0-windows-Release-x64](https://github.com/KhronosGroup/COLLADA2GLTF/releases)

Somewhere in the Asset Conversion Pipeline there is an error due to which Normal Maps are not working in gLTF! Can someone check what needs to be done to fix that? I have provided all the files for checking!

**Comment by lasalvavida** [comment]
This is fixed in #182.

![image](https://user-images.githubusercontent.com/2489570/39100471-021fbe1e-4659-11e8-9291-ba39d335f9d6.png)
