### ISSUE TITLE
UVs not Working for 2.0 branch

### ISSUE THREAD

**Issue by John-DeCorato-HZ** [KhronosGroup/COLLADA2GLTF#68]
Title is self-explanatory. Here is a test file and the output.

[test-cude.dae](https://github.com/KhronosGroup/COLLADA2GLTF/files/1219275/test-cude.txt)
[test-cude.gltf](https://github.com/KhronosGroup/COLLADA2GLTF/files/1219276/test-cude.txt)

**Comment by lasalvavida** [comment]
@John-DeCorato-HZ, the converter does optimize out unused texture coordinates to reduce the model size. Since your material contains no textures, they are removed.

**Comment by John-DeCorato-HZ** [comment]
Hmm, we have a dynamic asset pipeline where we add textures separately, so we don't save them with our models. Is there a workaround besides adding dummy textures to everything?

**Comment by lasalvavida** [comment]
So this is a pretty easy fix. I'll do it if I have time, but if someone else is willing to open a PR, this is a great beginner issue. The fix would entail adding something like a `preserveUnusedSemantics` boolean to [COLLADA2GLTF::Options](https://github.com/KhronosGroup/COLLADA2GLTF/blob/2.0/include/COLLADA2GLTFOptions.h), defining the option in the [argument parser](https://github.com/KhronosGroup/COLLADA2GLTF/blob/2.0/src/main.cpp#L31) and using the option to disable the call to [GLTF::Asset::removeUnusedSemantics](https://github.com/KhronosGroup/COLLADA2GLTF/blob/2.0/src/main.cpp#L156).

**Comment by John-DeCorato-HZ** [comment]
Excellent. I compiled a version myself without removeUnusedSemantics already but that option would make future proofing easy.

**Comment by lasalvavida** [comment]
Closed by #245
