### ISSUE TITLE
Verify that the handling of transparency is correct

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/COLLADA2GLTF#7]
The [shader generation in `commonProfileShaders.cpp`](https://github.com/KhronosGroup/COLLADA2GLTF/blob/5cbbe4674c16aa05cc613d8b7c50f4557b5af611/shaders/commonProfileShaders.cpp#L1207) currently contains the line

    fragmentShader->appendCode("color = vec4(color.rgb * diffuse.a, diffuse.a * %s);\n", "u_transparency");

which causes the fragment shader to set the fragment color to

    color = vec4(color.rgb * diffuse.a, diffuse.a * u_transparency);
    gl_FragColor = color;

The multiplication of the `rgb` components with the `diffuse.a` is probably *supposed* to be an alpha-premultiplication. But to my understanding, this is not right. **If** the color is intended to be prmultiplied, then this multiplication should also take the `u_transparency` into account. 

As an example, consider `color.rgb` to be (1,1,1), and `diffuse.a` to be 1.0, and `u_transparency` to be 0.5. Then the resulting `gl_FragColor` will be (1,1,1,0.5). If the `u_transparency` is 0.0, then the resulting `gl_FragColor` will be (1,1,1,0.0). Different sources ([1](http://webglfundamentals.org/webgl/lessons/webgl-and-alpha.html#-5-handling-images), [2](https://github.com/mrdoob/three.js/issues/5810#issuecomment-68065677), [3](http://stackoverflow.com/a/20365471), [4](https://www.opengl.org/registry/specs/NV/blend_equation_advanced.txt) ) consider a color in pre-multplied form to be "invalid" when either any RGB component is greater than the alpha component, or "ill-formed" when an RGB component is nonzero for an alpha of 0.0 (but finding a definite statement in the specs seems to be difficult). 

So the question is: 

**Is everybody sure that this implementation of the transparency handling is correct?**

---

Apologies for being so insistive, and although it already has become embarassing, I'd like to bring it up here, one last time (I promise), and if the answer to this issue is 
> "Everything is fine there, *you* are doing it wrong"

then I'll re-read everything that [I have read so far](https://github.com/javagl/JglTF/issues/6#issuecomment-262856689), until the penny eventually drops.

**Comment by pjcozzi** [comment]
I agree, this looks sketchy.  @tfili do you know off the top of your head if this is what is actually intended:
```glsl
color = vec4(color.rgb * diffuse.a, diffuse.a * u_transparency);
gl_FragColor = color;
```

**Comment by tfili** [comment]
@javagl @pjcozzi Just taking a quick look this is what I've scraped together:

If you look at the COLLADA spec (https://www.khronos.org/files/collada_spec_1_4.pdf) under the section `Determining Transparency (Opacity)` on page 223. You'll see that for `A_ONE` opaque mode the color is defined
```
result.r = fb.r * (1.0f - transparent.a * transparency) + mat.r *
(transparent.a * transparency)
result.g = fb.g * (1.0f - transparent.a * transparency) + mat.g *
(transparent.a * transparency)
result.b = fb.b * (1.0f - transparent.a * transparency) + mat.b *
(transparent.a * transparency)
result.a = fb.a * (1.0f - transparent.a * transparency) + mat.a *
(transparent.a * transparency) 
```
And in the `getTransparency` function [here](https://github.com/KhronosGroup/COLLADA2GLTF/blob/master/COLLADA2GLTFWriter.cpp#L209) we compute the value that will eventually become `u_transparency` to be `(transparent.a * transparency)`.

So with all that I think there is a bug and the actual shader code should be
```
color = vec4(color.rgb * u_transparency, diffuse.a * u_transparency);
```

Does that sound write to everyone?

**Comment by javagl** [comment]
> So with all that I think there is a bug and the actual shader code should be
> `color = vec4(color.rgb * u_transparency, diffuse.a * u_transparency);`
> Does that sound right to everyone?

I think that 

    color = vec4(color.rgb * diffuse.a * u_transparency, diffuse.a * u_transparency);
    //                       ^^this^^^

may not be omitted here, depending on where exactly the initial value of `diffuse.a` comes from (a texture or a uniform), but I'd have to match this with the writer code that you linked to. At least for the case of one of the VC model shaders ( https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/1.0/VC/glTF/VC2FS.glsl ), I think it is necessary for the case that someone set the `u_diffuse` uniform to something where `a < 1.0`, and *additionally* sets the `u_transparency` uniform to be < 1.0. 

---

**Iff** this is right, it would be in line with what I wrote in https://github.com/javagl/JglTF/issues/6#issuecomment-262810930 , and I think that this could eventually fix https://github.com/KhronosGroup/glTF/issues/576 . And, just as another pointer:  The *"Possibly unrelated..."* part from https://github.com/KhronosGroup/glTF-Sample-Models/issues/8 is actually related to *this* issue.

**Comment by lasalvavida** [comment]
2.0 implementation of shader generation (based on gltf-pipeline) should do this correctly - closing.
