### ISSUE TITLE
Execution Error on v2 Release

### ISSUE THREAD

**Issue by maozturk** [KhronosGroup/COLLADA2GLTF#77]
Hi,
I downloaded v2 release and I've trouble while executing COLLADA2GLTF-test command.
Here is the output of the command.
```
./COLLADA2GLTF-test 
./COLLADA2GLTF-test: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./COLLADA2GLTF-test)
./COLLADA2GLTF-test: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./COLLADA2GLTF-test)
./COLLADA2GLTF-test: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./COLLADA2GLTF-test)
./COLLADA2GLTF-test: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by ./COLLADA2GLTF-test)
./COLLADA2GLTF-test: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ./COLLADA2GLTF-test)
./COLLADA2GLTF-test: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./COLLADA2GLTF-test)
./COLLADA2GLTF-test: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./COLLADA2GLTF-test)
./COLLADA2GLTF-test: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./COLLADA2GLTF-test)
```

What could be the reason that I got this error? Could you please help me?

**Comment by lasalvavida** [comment]
Sounds like you need a newer version of libc6. Try getting the latest packages for your system. If you're on Oracle Linux, that should be `yum update`.

**Comment by maozturk** [comment]
I already updated the system but nothing changed.

**Comment by lasalvavida** [comment]
Then you're either going to have to use a newer version of your operating system, manually upgrade libc6, or build 2.0 from source using the 2.0 branch. You may have better luck building the 2.0 branch (I assume you are using master in #76) since it uses a reduced build of OpenCOLLADA.

**Comment by lasalvavida** [comment]
@maozturk, any luck?

**Comment by maozturk** [comment]
No, I couldn't update libc6 manually. I tried with 2.0 branch but I got the same error. I couldn't upgrade the system since upgrade for major releases require some tools and these tools are broken right now. Unfortunately I've nothing.

**Comment by lasalvavida** [comment]
> I tried with 2.0 branch but I got the same error.

Are you sure you go the same error/that you were on the 2.0 branch? 

The 2.0 build doesn't build `OpenCOLLADA/common/libBuffer` so maybe double check.

**Comment by lasalvavida** [comment]
Or does it build, but you can't run it?

**Comment by maozturk** [comment]
Here is the error after I executed `cmake ..` command in build directory.

> You have called ADD_LIBRARY for library pcre without any source files. This typically indicates a problem with your CMakeLists.txt file
> You have called ADD_LIBRARY for library COLLADABaseUtils without any source files. This typically indicates a problem with your CMakeLists.txt file
> You have called ADD_LIBRARY for library MathMLSolver without any source files. This typically indicates a problem with your CMakeLists.txt file
> You have called ADD_LIBRARY for library COLLADAFramework without any source files. This typically indicates a problem with your CMakeLists.txt file
> You have called ADD_LIBRARY for library expat without any source files. This typically indicates a problem with your CMakeLists.txt file
> You have called ADD_LIBRARY for library GeneratedSaxParser without any source files. This typically indicates a problem with your CMakeLists.txt file
> You have called ADD_LIBRARY for library COLLADASaxFrameworkLoader without any source files. This typically indicates a problem with your CMakeLists.txt file
> CMake Error at CMakeLists.txt:120 (add_subdirectory):
>   The source directory
> 
>     /home/maozturk/Desktop/collada/collada2gltf/COLLADA2GLTF/COLLADA2GLTF-2.0/dependencies/ahoy
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> -- Configuring incomplete, errors occurred!
>

**Comment by lasalvavida** [comment]
You have to run `git submodule update --init --recursive` to pull in the submodules. Do that then try the build again.

**Comment by maozturk** [comment]
Same result :(

**Comment by lasalvavida** [comment]
If you look in the folder `dependencies/ahoy`, are there files in there?
Did the `git submodule update --init --recursive` command give you an error?

**Comment by lasalvavida** [comment]
Closing with #76.
