### ISSUE TITLE
Generated gltf is invalid

### ISSUE THREAD

**Issue by sloschi** [KhronosGroup/COLLADA2GLTF#90]
Hi!

I downloaded a simple low poly deer model in COLLADA v1.5 format and converted it to gltf. 

`collada2gltf.exe -f deer.dae -r -e`

The [glTF Validator](http://github.khronos.org/glTF-Validator/) shows some errors and i cannot load it in the [glTF Viewer](https://gltf-viewer.donmccurdy.com/) (again, due to some errors). 

[deer.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/1296229/deer.zip)

I would appreciate it if someone could have a look at those files 👍

**Comment by lasalvavida** [comment]
Hi @sloschi, the validator and viewer you linked to only support glTF 2.0. You are using the 1.0 converter which produces glTF 1.0. Try again with the 2.0 converter using the 2.0 release or by building the 2.0 branch.

**Comment by sloschi** [comment]
ah, silly me. i assumed that the master branch would generate gltf 2.0. I built the 2.0 branch and everything works! Thanks!
