### ISSUE TITLE
2.0: flag order matters

### ISSUE THREAD

**Issue by jeremyabel** [KhronosGroup/COLLADA2GLTF#93]
-db outputs a gltf file, but -bd outputs a glb file. Flag order shouldn't matter, should it?

**Comment by lasalvavida** [comment]
Ahoy doesn't support joined flags like that. `-db` will be read as just `-d` and `-bd` will be read as just `d`. It should probably either exhibit the behavior you're expecting, or throw an error. I'm in favor of the former and I opened up https://github.com/lasalvavida/ahoy/issues/3.

**Comment by jeremyabel** [comment]
ahh, gotcha. It does behave correctly then, I'll close https://github.com/KhronosGroup/COLLADA2GLTF/issues/92

**Comment by lasalvavida** [comment]
I am going to close this since it is not a COLLADA2GLTF issue and is fixed in the latest Ahoy https://github.com/lasalvavida/ahoy/pull/5.
